server:
  port: 8080
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/AcademicKG?serverTimezone=GMT%2b8&allowMultiQueries=true
    username: zsl
    password: Lish145210@
  # 邮箱配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 958724504@qq.com
    password: tafvnpjklfidbahi
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

milvus:
  host: localhost
  port: 19530
